version: "3"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    env_file: # 環境変数
      - ./mysql/db.env # DB接続用MySQL関連
    volumes:
      - ./mysql/data:/var/lib/mysql # データの永続化
      - ./mysql/log:/var/log/mysql # logの永続化
    ports:
      - 3306:3306

  dbclient:
    image: phpmyadmin/phpmyadmin
    container_name: dbclient
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=dev_usr
      - PMA_PASSWORD=dev_usr_pass
    links:
      - mysql
    ports:
      - 4200:80
    volumes:
      - ./dbclient/sessions:/sessions
    depends_on: # 起動する順番
      - mysql # 「mysql」の後で起動

  java: # Spring Bootのコンテナ
    build: ./java # Dockerファイルのパス
    container_name: java
    env_file: # 環境変数
      - ./mysql/db.env # DB接続用MySQL関連
    tty: true
    working_dir: /app
    volumes: # 永続化
      - ../spring_prj:/app # Spring Bootのプロジェクト
    ports: 
      - 8080:8080
      - 5050:5050 # デバッグ用
    depends_on: # 起動する順番
      - mysql # 「mysql」の後で起動
